### ISSUE TITLE
deposit(tokenAddress0, tokenAddress1, amount0, amount1)->reponse

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#10]
Create function deposit(tokenAddress0, tokenAddress1, amount0, amount1)->reponse to make user sign transaction and deposit the given amounts It returns a response object (a json) which indicates if the transaction was successful or if it has been an error.

**Comment by chopan123** [comment]
You may be able to deposit any amount to the contract. Make sure function is called on blockchain
