### ISSUE TITLE
getLPTokensAmount(token0Address, amount0, token1Address, amount1) -> int | bigint:

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#11]
Create function getLPTokensAmount(token0Address, amount0, token1Address, amount1) -> int | bigint: Given the addresses and amounts to deposit it returns the LP tokens that user will receive after depositing

**Comment by chopan123** [comment]
https://github.com/Uniswap/v2-sdk/blob/main/src/entities/pair.ts

**Comment by esteblock** [comment]
Also show in frontend
