### ISSUE TITLE
Swap: When calculating expected amount, we should show a "charging" empty field

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#111]
Currently, it takes around 1 sec to calculate the expected output amount.
See in the following video:
[Screencast from 13-09-23 07:05:58.webm](https://github.com/soroswap/frontend/assets/2274485/15d6ef30-d008-4e18-9d45-2af3df1bc404)

This can cause confusion. It's better than any time the user types somethig we
- delete the old value
- set a "waiting value" (as it is currently shown in the future dollar value)
- when we have a response, now show the expected output (or input, depending on the case)

**Comment by esteblock** [comment]
Otra cosa que pasa, es que mientras uno tipea un valor de digamos, 4 dígitos... 4 o múltiples funciones quedan en espera y trabajando; y llegan todas las respuestas de una sóla vez

Deberíamos hacer que mientras el usuario cambie un input value; todas las otras búsquedas se cancelen y comience una nueva, y no que continúen en el  background

Ver cómo funciona en Uniswap https://app.uniswap.org/swap

**Comment by abstract829** [comment]
El problema es que el código esta mal y genera muchas llamadas extra 

por ejemplo en este caso el expected output lo generan matematicamente en el front, asique  una vez ya obtenido el par y reservas, el output es solo matematico por lo que no deberia hacer mas llamadas, pero estaba haciendo las llamadas cada vez que cambiaba el input 

https://vimeo.com/881447129 (antes)

hice refactor de varias cosas y ahora deberia dar el input instantaneamente

https://vimeo.com/881447114 (ahora)

todavia se pueden mejorar cosas de todos modos, pero ya no se vuelve loco con las llamadas

por lo que vi es muy probable que les este ocurriendo esto en otras partes de la app igualmente 

comentame si te va mejor ahora @esteblock

**Comment by esteblock** [comment]
@abstract829 mucho mejor!
De todas maneras esto no es una buena práctica en DeFi, porque el precio puede estar cambiando en cuando el usuario se demora en elegir lo que quiere hacer.... 
Pero por ahora nos acomoda y genera una buena experiencia de usuario. 
Asi que lo cierro!
