### ISSUE TITLE
Swap Overview

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/frontend#122]
# Overall TODOs in Swap section

This points are organized by priority in my opinion

- [x] If i select tokens that doesnt have a pair and input any amount into it the app throws an error that must be fixed, is related to the app looking for the pair address but failing in the process
- [x] When rejected its gets stuck in "waiting to sing transaction" should say "Rejected by user" or something like that
- [x] When selecting tokens to swap if the pair exists and you enter an amount it will always say "Swap" even if the pair doesnt have any liquidity... We have to check if the pair have any reserves and show "Insufficient liquidity for this trade". It does work when the pair does have liquidity in it, but when its empty it always says "Swap"
- [x] useSwapCallback Line: 59 the same with "View on explorer" issue, here we should get the txhash
- [x] When swap is completed says "View on explorer" this redirects to google.com and should get the explorer link, not sure if this is possible yet, maybe just copy to clipboard the txHash
- [x] Add a default token, probably it should be XLM token on the active network `src/pages/swap.tsx Line: 91`
- [ ] SwapDetailsDropdown network fee is not working
- [x] AdvancedSwapDetails -> Get slippage and do `(outputAmount * (1-slippage%))` `src/components/Swap/AdvancedSwapDetails.tsx Line: 134`
- [x] fromExactInputGetExpectedOutput -> this function does a .dp(7) which forces the answer to have 7 decimals, this should not be hardcoded and should the token decimals
- [x] useSwapCallback is multiplying the inputAmount by 1.5, this is not good but a workaround to make the swaps go through, when implementing the router this should be different
- [x] Use pathname to get prefilled tokens `src/pages/swap.tsx Line: 84`
- [ ] Create USDPrice function, to get the tokens amount in usd, this is not possible yet
- [ ] `src/hooks/useBalances.tsx Line: 83' Should also use USDPrice function in here
- [x] Review the calculation or the decimal conversion of price impact (almost always shows ~67%)
- [ ] #179
![Image](https://github.com/soroswap/frontend/assets/18266350/3ecc54b8-1dab-4fc1-9556-5f559c32e99d)

**Comment by abstract829** [comment]
I will move this to test

Created #178 for:

-useSwapCallback Line: 59 the same with "View on explorer" issue, here we should get the txhash

-When swap is completed says "View on explorer" this redirects to google.com and should get the explorer link, not sure if this is possible yet, maybe just copy to clipboard the txHash

already created the copy tx hash component but need to figure out how we get the tx hash from the result


this is related to #115 so will be using that ticket

-SwapDetailsDropdown network fee is not working

and  this is related to #103 so will be using that also

-Create USDPrice function, to get the tokens amount in usd, this is not possible yet
-`src/hooks/useBalances.tsx Line: 83' Should also use USDPrice function in here
-Black Square is appearing sometimes:

**Comment by esteblock** [comment]
Will check this now

**Comment by abstract829** [comment]
@esteblock  

i saw [#166](https://github.com/soroswap/frontend/issues/166)  and i think

- AdvancedSwapDetails -> Get slippage and do (outputAmount * (1-slippage%)) src/components/Swap/AdvancedSwapDetails.tsx Line: 134

was wrong ? since expected amount should not be with slippage applied ? or is it correct ?

**Comment by esteblock** [comment]
> @esteblock
> 
> i saw [#166](https://github.com/soroswap/frontend/issues/166) and i think
> 
>     * AdvancedSwapDetails -> Get slippage and do (outputAmount * (1-slippage%)) src/components/Swap/AdvancedSwapDetails.tsx Line: 134
> 
> 
> was wrong ? since expected amount should not be with slippage applied ? or is it correct ?

@chopan123 is looking at this right now
