### ISSUE TITLE
Main Liquidity Overview

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/frontend#123]
# Liquidity Main Page

We are doing a workaround here to get the LP positions, getting all the pairs from the api and looping through them to get which of those the user have balances in, and then getting the data from the one the user has balances

- [x] LP position modal should also show tokens amount
- [x] Remove liquidity is sending to add liquidity

**Comment by joaquinsoza** [comment]
![Image](https://github.com/soroswap/frontend/assets/34905663/14714737-8233-4d4b-b3b9-ac1bd70d788b)

Example of what information pancakeswap shows

**Comment by esteblock** [comment]
@abstract829 Currently info is confusing.
It's saying "No liquidity found".... but in fact it's loading. We should add a loader




![Image](https://github.com/soroswap/frontend/assets/2274485/b7ec7e53-1a00-4083-a613-c10029847afd)

... and after 5 seconds all my LP positions appear

**Comment by abstract829** [comment]
added the loader

**Comment by esteblock** [comment]
Finally, please set the connect wallet button with an active colour,
Está con color tipo error o desactivado @abstract829

**Comment by abstract829** [comment]
changed
