### ISSUE TITLE
Add Liquidity Overview

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/frontend#124]
# Add Liquidity

- [x] Bunch of warning in the flow that needs to be fixed
- [x] Supply button should not say "supply" until both tokens have an amount in
- [x] Main supply button should say "Create" if the pair does not exists
- [x] Main supply button should say "Not enough balance" if the balance get over the one the user holds
- [x] Confirm modal says "You are creating a pool" which is wrong also the confirm button says "Confirm swap"
- [x] Confirm modal needs some work, also after "Confirm" is pressed it appears an alert saying success, should be one of the apps notifications
- [x] Confirm modal should change to a loading screen and suggest the user to go to the wallet and sign the transaction, it should also close by itself...
- [x] When tokens are not selected, user should not be able to go to modal

**Comment by chopan123** [comment]
"You are the first to add liquidity" if the pair exists but there is no liquidity
"Add liquidity" If the pair exist and there is liquidity
"You are creating a pool" if the pair does not exist
