### ISSUE TITLE
Mint section: delete

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/frontend#125]
# Mint Section
- [x] Hide (dont delete the code)
- [x] Hide in desktop & mobile menu
# Balance Section:

- [x] Make it look and feel like the rest of the app.
- [x] Make sure it is desktop & mobile menu
- [x] Show token icons before token symbol ([icon][USDC] [amount])
- [x] IN the section itself show "Your Balances:"
- [x] Currently it does show "Mint test tokens" when wallet is not connected. The description should say "Connect your wallet to see your test tokens balances", and the button should say "Connect Wallet" ( and behave as connet wallet button)

**Comment by esteblock** [comment]
@joaquinsoza please delete or hide the mint section
