### ISSUE TITLE
Breaks when pair does not exist

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#140]
When we are adding liquidity for a pair does not exist, the app is breaking

**Comment by esteblock** [comment]
-  you should first ask to the factory if pair exist
- if pair exist, shows info about the pair
- if pair does not exist, tells the user that he will create the pair, without asking info for an unexisting pair

**Comment by abstract829** [comment]
When the pair doesn't exists is giving this error on add liquidity

![Captura de pantalla 2023-11-04 a la(s) 10 13 06](https://github.com/soroswap/frontend/assets/56497105/b325cf11-1ab2-41d7-a4cd-2447c9a7aeb2)
