### ISSUE TITLE
Swap pup-up should show the exact about that was swapped

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#149]
Should show the exact amounts that where swapped

**Comment by abstract829** [comment]
this should be fixed when updating the packages of soroban-react

**Comment by esteblock** [comment]
Hola @abstract829... se supone que ya lo actualizaste. Me sale info confusa.

Comienzo con: 
XRP : 9989900
ARST : 9990098.7158034


QUiero hacer swap de exactamente ARST : 8.7158034 por una cantidad de XRP aproximada

![Screenshot from 2023-11-07 16-41-51](https://github.com/soroswap/frontend/assets/2274485/f1ec23aa-4b48-467e-8fb9-30ec3aa3f90a)
![Screenshot from 2023-11-07 16-41-58](https://github.com/soroswap/frontend/assets/2274485/b8fd5cb6-7791-4aea-b976-366e8b11ca6a)
![Screenshot from 2023-11-07 16-42-05](https://github.com/soroswap/frontend/assets/2274485/39aeae92-149b-4d47-b7c6-70beae517eb4)

El pop up muestra algo nada que ver:
![Screenshot from 2023-11-07 16-42-14](https://github.com/soroswap/frontend/assets/2274485/cd9b7d5f-c54b-4c0d-a42c-96ddc33d0d49)


** Termino con un balance esperado, pero nada que ver con el pop up**
XRP : 9989908.8562822
ARST : 9990090

**Comment by abstract829** [comment]
@esteblock hola, si tenia una division de mas, con el pr de ahora se soluciona

**Comment by esteblock** [comment]
Está bien ahora!
