### ISSUE TITLE
Error Creating Pair when add liquidity and pair doesn't exists

### ISSUE THREAD

**Issue by abstract829** [soroswap/frontend#160]
When the pair doesn't exists is giving this error on add liquidity

![Captura de pantalla 2023-11-04 a la(s) 10 13 06](https://github.com/soroswap/frontend/assets/56497105/b325cf11-1ab2-41d7-a4cd-2447c9a7aeb2)

**Comment by esteblock** [comment]
Para cuando vuelvas @joaquinsoza , no tiene urgencia, pero sí tiene que estar antes de fin de año (mainnet)
Por ahora el hack que hicimos fue crear todos los pares desde el core

**Comment by esteblock** [comment]
No crear los pares al correr el script. Trabajar en una branch independiente y hacer funcionar

**Comment by joaquinsoza** [comment]
Create pair and add liquidity is working perfectly. BUT i cant see the pairs created for example XLM and XTAR in the main liquidity page because the app is getting the data from the pairs in the api...

**Comment by joaquinsoza** [comment]
New functions created to get all the pairs from the factory contract

**Comment by esteblock** [comment]
Not possible to test

**Comment by joaquinsoza** [comment]
Working
