### ISSUE TITLE
Add Liquidity Changes

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#165]
- [x] Share of pool percentage should appear in the detail section, not as 2236.0679775 (100.00%) in the main LP token information. There is a "share of pool" section empty now. Esto significa que en vez de decir ""100 (100.00%) XRP/ARST Liquidity Pool Token",", debería decir ""100 XRP/ARST Liquidity Pool Token"... y el porcentaje aparecer en su sección en la parte de detalles
- [x] #167
- [x] Así como existe el subtítulo "you sell / you receive" en el swap, antes de la info principal de "100 (100.00%) XRP/ARST Liquidity Pool Token", debería decir "You will mint"
- [x] Cambiar "XRP/ARST Liquidity Pool Token" por "XRP/ARST Liquidity Pool Token
- [x] Agregar el uso de "Max" (use max balance) al momento de agregar liquidez
- [x] Cuando el par no existe, está aceptando 0 en el segundo token

**Comment by esteblock** [comment]
@abstract829 
I am having 0 as "Share of Pool"
![Screenshot from 2023-11-07 16-09-48](https://github.com/soroswap/frontend/assets/2274485/6c711344-61e6-4ed2-9cb6-65849be5a62e)

**Comment by esteblock** [comment]
> @esteblock siempre te muestra 0, o solo ese caso ? puede ser por que la cantidad sea muy baja en relacion a lo que hay en la pool ?

puede ser, voy a hacer experimentos para ver

**Comment by esteblock** [comment]
Es verdad. En este caso, deberíamos etener un máximo de 3 decimales para los porcentajes, siendo el mínimo0.001%
Y si es menor al mínimo debería decir "<0.001%"

**Comment by abstract829** [comment]
ahora esta con 3 decimales, y se agrego <0.001% cuando es menor
