### ISSUE TITLE
Minimum Received / Pay at Most

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#166]
When swapping, currently if you fix the input amount, in the confirmation modal says "Minimum Received"... which is not too bad, but the amount is wrong. It is showing the expected amount to receive. The minimum received it is calculated using the slippage.. 
- [x] Should be the same as `amount_out_min`

See https://github.com/soroswap/frontend/blob/45506bf301ba89e04df8a8dc9340448432ff62a8/src/hooks/useSwapCallback.tsx#L55 and factorLess and factor More

- [x]  Also, when you fix the output amount, the "Maximum sent" it's fixed to the "expected output". It should be the same as `amount_in_max`.

Finally. Titles should change

- [x] Use "Receive at least" instead of "minimum Received"

- [x] Use "Pay at Most" instead of "Maximum sent"

**Comment by esteblock** [comment]
Hola. No sé si fué una confusión, pero también agregaste el slippage en el "Expected Amount" de la info principal del swap

![Screenshot from 2023-11-08 15-43-49](https://github.com/soroswap/frontend/assets/2274485/87ad7c22-dfd3-4fc9-856c-69230d7cdb62)

Ese expected amount debe ser el mismo que aparece arriba

**Comment by abstract829** [comment]
si, eso es lo que comentaba en [#122](https://github.com/soroswap/frontend/issues/122) 

salia en un item hacerlo pero luego vi que quizas estaba mal, ya lo revertí
