### ISSUE TITLE
Small issues: Overview 7 Nov

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#171]
- [x] on / Change "Your Balance" for "Your test token's balance"
- [x] on / Add commas to balance. Balance show 7,500,000 instead of 7500000
- [x] Select a token menu is allways looking for token list, two options:
    - [ ] Is there a way that this is loaded at the beggining and not loaded again?
    - [ ] Add a loading component (wheel) when loading tokens, show loading instead of "no results found"
- [x] on /liquidity Add a loading wheel when fetching for liquidity positions. Instead of "No liquidity found."
- [x] On /swap. When there is no liquidity in a pair:
  - [x] Disable Swap button with the message:"Insufficient liquidity for this trade." 
  - [x] Disable amounts and the "0" number should be in gray colour 
  - [x] Disable SwapDetailsDropdown (for example: "1 BRL = 0 USDC " and "Network fee; ~$? Price Impact, NaN% Expected output, 0 BRL BRL logo") and 
  - [x] show "Fetching best price..." instead of "1 BRL = 0 USDC " on SwapDetailsDropdown
- [x]  on / When minting, the "loading" circle should Say "Minting USDC [loading circle]"
- [x] on /swap in modal "Minimum received" should take into account the slippage
- [x] on /swap in modal  "Maximum sent" should take into account the slippage

**Comment by abstract829** [comment]
@chopan123 puede que 

 -Is there a way that this is loaded at the beggining and not loaded again?
 -Add a loading component (wheel) when loading tokens, show loading instead of "no results found"

se haya resuelto con los cambios que han habido ? o no lo supe reproducir

**Comment by abstract829** [comment]
Ahora los input se deshabilitan cuando no hay liquidez, cambie lo del dropdown tambien pero enverdad nunca llega a salir por que los input se activaba cuando se escribia en los input, y ahora nunca se llega a escribir ya que estan deshabilitados

![Image](https://github.com/soroswap/frontend/assets/56497105/a4d9caa3-6e3a-4a69-a469-2a5eae4a4593)

**Comment by abstract829** [comment]
Lo de 

-Is there a way that this is loaded at the beggining and not loaded again?
-Add a loading component (wheel) when loading tokens, show loading instead of "no results found"

no lo he podido reproducir, pasare a to test
