### ISSUE TITLE
Implement Network Connector of soroban-react to read blockchain data without connecting wallet

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#175]
https://github.com/paltalabs/soroban-react/issues/12

**Comment by esteblock** [comment]
Revisa https://github.com/esteblock/multichain-dapp

**Comment by abstract829** [comment]
agregado, y cuando esta en prod se coloca testnet como activechain, sino standalone

```bash
const activeChain: WalletChain = process.env.NODE_ENV === 'production' ? testnet : standalone;

```




https://github.com/soroswap/frontend/assets/56497105/691aff32-69e9-4263-b2be-bfbe418a44e8
