### ISSUE TITLE
Get tx hash from the contractinvoke result and use in clipboard component

### ISSUE THREAD

**Issue by abstract829** [soroswap/frontend#178]
Figure out how to get the tx hash from the result and add it to the CopyTxHash component

**Comment by esteblock** [comment]
Cool! Let's allways show the "Copy transaction hash" message.
But please also add:
1.- If we are in testnet:  add a link into the explorer: **See transaction in explorer**
https://stellar.expert/explorer/testnet/tx/a8f6c2820df5e3d4fea439dc2f270c83889e48dcc56d2e9de03caa53353fff2a
2.- If we are in public (not yet): **See transaction in explorer**
https://stellar.expert/explorer/public/tx/a8f6c2820df5e3d4fea439dc2f270c83889e48dcc56d2e9de03caa53353fff2a

**See transaction in explorer** should be under the "Copy transaction hash" message.

**Comment by esteblock** [comment]
Also, I am copying "[object Object]" @abstract829

**Comment by abstract829** [comment]
@esteblock yes, we need to know how to get the tx hash from the result and then pass to the component, i dont remember what is sending now

**Comment by esteblock** [comment]
> @esteblock yes, we need to know how to get the tx hash from the result and then pass to the component, i dont remember what is sending now
> 
> do you know how to get the tx hash ?
> 
> the response looks like this:
> 
> ![Image](https://user-images.githubusercontent.com/56497105/281452683-0d46e90a-ed47-4d9f-a199-060941d584ab.png)
> 
> and i am using https://laboratory.stellar.org/#xdr-viewer to see if something contains the tx hash but seems to not be there

Will check. You can allways use https://laboratory.stellar.org/ to translate XDR while developing

**Comment by abstract829** [comment]
added the tx hash to the clipboard and view on explorer button on testnet or public

**Comment by abstract829** [comment]
ahora va en minuscula

```bash
if (activeChain.name === testnet.name || activeChain.name === public_chain.name) {
    setExplorerLink(getExplorerUrl({ chain: activeChain.name?.toLowerCase() as string, txHash }));
  }
```

```bash
const getExplorerUrl = ({ chain, txHash }: { chain: string; txHash: string }) => {
  return `https://stellar.expert/explorer/${chain}/tx/${txHash}`;
};
```
