### ISSUE TITLE
Insiffucient Liqudity Message in wrong situation

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#181]
My situation:
LP Reserves: 
USDC 500.7511267
XLM 2000

My Balance 2M+ each, is enough
I want to swap XLM for USDC.

If I start typing 4 digits, says "Insufficient Liquidity", even if the expected output amount is less than the USDC reserve
![Screenshot from 2023-11-08 15-52-49](https://github.com/soroswap/frontend/assets/2274485/43665f72-0d95-499e-8659-9bf2f1deb976)

Price impact can be higher than 100%

What are the rules for Insufficient Liquidity in this case @abstract829 ?

**Comment by abstract829** [comment]
@esteblock 
was not validating the reserve token vs the input address

added this and should be fine

```
    if (reserves?.token0 === currencyA?.address) {
      reserveA = formatTokenAmount(reserves?.reserve0 as BigNumber);
      reserveB = formatTokenAmount(reserves?.reserve1 as BigNumber);
    } else {
      reserveA = formatTokenAmount(reserves?.reserve1 as BigNumber);
      reserveB = formatTokenAmount(reserves?.reserve0 as BigNumber);
    }

    const insufficientLiquidity =
      Number(inputA) > Number(reserveA) || Number(inputB) > Number(reserveB);
```

**Comment by esteblock** [comment]
Hola @abstract829 
```
const insufficientLiquidity =
      Number(inputA) > Number(reserveA) || Number(inputB) > Number(reserveB);
```
Sólo es necesario `Number(inputB) > Number(reserveB);`, porque es sólo el B que será output.
el token A es lo  que el usuario va a insertar

**Comment by abstract829** [comment]
lo cambiè a ```Number(inputB) > Number(reserveB);```
