### ISSUE TITLE
Swap: Handle big output amounts

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#192]
- When output amount is equal to current reserve we are having a strange situation with "Infinity". In the next example, the Liquidity Pool has exactely 1,000 units of ARS

![Screenshot from 2023-11-14 12-36-13](https://github.com/soroswap/frontend/assets/2274485/e13dfd9e-d800-47ec-83d2-f2842eab7dbf)

- When output amount is bigger than current reserve, we are showing negative numbers in expected input amount:

![Screenshot from 2023-11-14 17-24-10](https://github.com/soroswap/frontend/assets/2274485/b19749dd-d4f6-4840-8fe8-ab2691faf2e2)

- Message "insufficient liquidity" is good

- [x] We should have, for both situations explained above a gray (or disabled) colour number "0" in expected input amount.
- [x] Also, in both situations, the "price section" should be hidden

**Comment by abstract829** [comment]
Now if the output is bigger or equals than the reserves, the input is disabled and the price section is hidden

example: XLM reserves are 1000

https://github.com/soroswap/frontend/assets/56497105/9fefc8a0-f801-4e0d-879d-102281bb2981
