### ISSUE TITLE
Swap: Prices should be average price and not marginal price

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#193]
Current situation:
We are allways showing maringal price. (In the example, the equivalent amount of XLM if we want an exactely output/input amount of ARS).. In the example we are selling  1.0040131 XLM to receive 1 ARS, so price is 1 ARS =  1.0040131 XLM 

![Screenshot from 2023-11-14 17-32-15](https://github.com/soroswap/frontend/assets/2274485/116f2e0e-52cd-4cb1-b47b-50d024337cd7)

This is good.

However, what is bad is when we want to have a different output, let's say 100 ARS... we should pay 111.4454 XLM
![Screenshot from 2023-11-14 17-33-35](https://github.com/soroswap/frontend/assets/2274485/2abe8c60-7e75-4d23-8ad3-ebded99b4163)

Hence, the correct average price should be 1 ARS = (111.4454 / 100) XLM = 1.11445.
We should display 1 ARS = 1.11445 XLM, and not the old "marginal price" of "1 ARS =  1.0040131 XLM "

**Comment by abstract829** [comment]
Before was showing always the expected amount of 1 token

Now divides the input/ouput or viceversa to show the correct rate

Also fixed in the swap modal footer "Exchange rate"

https://github.com/soroswap/frontend/assets/56497105/34127b9f-b03b-434d-87ba-fd2bb6b82190
