### ISSUE TITLE
Add an asset by it's contract address

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#197]
It's ok that suggested assets comes from the API, but we should be able to paste new contact address

- [ ] Be sure that we can add liquidity to non existing pairs
- [x] Find a way to verify if a contract address is a token
- [x] Implement

**Comment by esteblock** [comment]
Solved in https://github.com/soroswap/frontend/pull/210

**Comment by joaquinsoza** [comment]
All working, there is an error now after providing liquidity to this tokens. Main liquidity page wont load correctly

**Comment by esteblock** [comment]
Hei @joaquinsoza 
We are supposed to try this with tokens that are not in the menu.
Please take out these "random tokens" from the menu
![Screenshot from 2023-12-27 23-02-28](https://github.com/soroswap/frontend/assets/2274485/eee9d45f-30f4-41e2-a618-3ce2aaf2871a)

**Comment by esteblock** [comment]
If I paste any address (that is not a token, not even a contract, I see a bug)
![Screenshot from 2023-12-27 23-08-16](https://github.com/soroswap/frontend/assets/2274485/407beab0-65de-4409-b04e-aa5fbdbc8234)

**Comment by esteblock** [comment]
![Screenshot from 2023-12-27 23-11-30](https://github.com/soroswap/frontend/assets/2274485/504dbd4e-a792-4aef-8120-7a623709bfce)


There are a lot of errors when trying to paste something that is not a token

**Comment by joaquinsoza** [comment]
All working, only thing missing is being able to add the token by SYMBOL:ISSUER

**Comment by joaquinsoza** [comment]
Now you can search an asset by its code and issuer, and it will be wrapped into a soroban address
