### ISSUE TITLE
soroswap.finance sólo debería soportar Testnet

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#198]
Actualmente las chains que se soportan están en:
https://github.com/soroswap/frontend/blob/365914d2ee6376a556d1e549b5fe098888a771df/src/soroban/MySorobanReactProvider.tsx#L7

Esto es un problema, porque por un lado queremos desarrollar de manera local usando Standalone, Futurenet y/o Testnet.
Pero en producción sólo deberíamos soportar Testnet, o sólo Mainnet/Testnet en el futuro

Qué hacer?
Hacer que esto también esté definido en el .env y dejar preparado los .env.production y .env.development

**Comment by abstract829** [comment]
ahora detecta cuando esta en produccion y solo usa testnet

```bash
const chains: ChainMetadata[] = process.env.NODE_ENV === 'production' ? [testnet] : [sandbox, standalone, futurenet, testnet];

```
