### ISSUE TITLE
Add network name in menu

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#203]
in the top right corner, we should see the address and then the network we are connected to:
[light/dark mode] [ network name] [ connect wallet / address]

Like in Uniswap:
![Screenshot from 2023-11-20 11-11-55](https://github.com/soroswap/frontend/assets/2274485/cc101b61-5ae3-41bd-b651-a280205aa744)

Or 1inch

![Screenshot from 2023-11-20 11-14-38](https://github.com/soroswap/frontend/assets/2274485/9b3d2ba8-ecd0-46e6-831f-d7cd9a8fc4d3)

![Screenshot from 2023-11-20 11-10-11](https://github.com/soroswap/frontend/assets/2274485/79b04242-3884-481c-b696-146df9a06294)

In mobile, we should also see the name, at the left of the burger menu:

![Screenshot from 2023-11-20 11-17-07](https://github.com/soroswap/frontend/assets/2274485/8c2be85b-5619-4d5a-8a17-ebe147212d25)
![Screenshot from 2023-11-20 11-16-56](https://github.com/soroswap/frontend/assets/2274485/d9d16080-5d9c-4cb4-aa81-1c419d68fba0)
![Screenshot from 2023-11-20 11-16-09](https://github.com/soroswap/frontend/assets/2274485/2e7979bb-3092-4c24-b14a-6d5281145fad)

Network name should be:
- default chain if wallet is not connected
- if wallet is connected, the wallet the user chooses in Freighter

**Comment by abstract829** [comment]
Added active chain in the header



https://github.com/soroswap/frontend/assets/56497105/18e8d644-83dd-4519-8b2e-cf38cf59edaa
