### ISSUE TITLE
Integration of Custom User Tokens with Existing Token Management System

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#212]
**Objective:**
To improve the app's functionality by allowing users to add custom tokens, which should be seamlessly integrated with the existing token list used throughout the app, such as in the SearchModal, Balances, etc.

**Current Implementation:**
- `useTokens`: Retrieves the list of tokens from the API.
- `useDefaultActiveTokens`: Merges the API tokens.
- `useToken` / `getToken`: Methods for retrieving token information.

**Issues Identified:**
- `useToken` effectively fetches tokens from the combined list or the network but isn't loop-friendly.
- `getToken` is limited to network searches and doesn't align with `useToken` in functionality.

**Proposed Enhancements:**
1. **Custom Token Addition and Persistence:**
   - Implement a feature for users to add custom tokens.
   - Store these user-added tokens in local storage.

2. **Integration with Existing Token System:**
   - Develop a new hook, `useUserAddedTokens`, to retrieve user-added tokens from local storage.
   - Update `useDefaultActiveTokens` to include user-added tokens in its merged list, combining API tokens and user-added tokens.

3. **Consistent Token Retrieval Logic:**
   - Revise `getToken` to function similarly to `useToken`, allowing it to retrieve tokens from the merged list in `useDefaultActiveTokens` as well as from the network.
   - Ensure `getToken` can be used in loops, addressing current limitations observed in `useGetLpTokens.ts`.

**Expected Outcome:**
The integration of user-added tokens with the existing token management system will provide a more comprehensive and user-friendly experience. Users will be able to manage a personalized set of tokens, ensuring consistent and efficient access across different parts of the app.

**Comment by joaquinsoza** [comment]
Description updated

**Comment by abstract829** [comment]
refactor and added hooks:

useApiTokens -> Returns only tokens from the api
useUserAddedTokens -> Returns only user added tokens
useAllTokens -> Returns both
useToken -> Returns token from the "useAllTokens" or find in the network

https://github.com/soroswap/frontend/assets/56497105/6e42ecdd-6502-4bf2-be3a-09a639ec9573
