### ISSUE TITLE
Frontend - add errors if no tokens was minted

### ISSUE THREAD

**Issue by MattPoblete** [soroswap/frontend#226]
Currently, if there are no minted tokens, the frontend displays a successful modal, leading to false positives on tests.

![Image](https://github.com/soroswap/frontend/assets/86752543/cdbbf1e8-dac5-47d1-98d1-2e16bc43cc68)

**Comment by abstract829** [comment]
success snackbar

![Image](https://github.com/soroswap/frontend/assets/56497105/56f48a07-81e3-40c8-958d-fce7719b7bb7)

error (0 minted)



![Image](https://github.com/soroswap/frontend/assets/56497105/b65420a3-42ca-4862-a2ac-5c585c8115f4)
