### ISSUE TITLE
Balances on swap not being updated automatically

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/frontend#227]
## Balances not being updated automatically
![Image](https://github.com/soroswap/frontend/assets/34905663/cb62ec7a-380e-4399-8e0f-1a72400d742e)

Balances on swap component should be updated automatically after swapping.
This was working before, not sure what happened here and its not working now.

**Comment by abstract829** [comment]
fixed

https://github.com/soroswap/frontend/assets/56497105/e7d9c92e-29d4-41d7-9d24-22433d4e05cb
