### ISSUE TITLE
Crash when trying to wrap without having wallet connected

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#245]
**Describe the bug**
Crash when trying to wrap without having wallet connected

**To Reproduce**
1. Cp .env.local.example .env (this is to set by default standalone)
2. Copy a non wrapped stellar classic asset from http://localhost:8010/api/random_tokens in swap
3. Clicc Wrap

**Expected behavior**
ALL ations that require a wallet to be connected should go to a function that checks if the wallet is connected or not and proposes the user to connect the wallet first

**Screenshots**
![Screenshot from 2024-01-17 13-45-53](https://github.com/soroswap/frontend/assets/2274485/fcc8dc26-4bdc-44be-b26e-872de2682aee)

**Comment by esteblock** [comment]
Assigned: @joaquinsoza 
Reviewer: @esteblock

**Comment by joaquinsoza** [comment]
#251
