### ISSUE TITLE
Chrash when trying to wrap and not having funded the wallet

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#246]
Similar to #245 

![Screenshot from 2024-01-17 13-47-06](https://github.com/soroswap/frontend/assets/2274485/3ba3d7d6-c5d6-4815-8ff2-fa6013155ee6)

**Comment by esteblock** [comment]
Assigned @joaquinsoza 
Reviewer: @esteblock

**Comment by joaquinsoza** [comment]
#251
