### ISSUE TITLE
Frontend: Implement Soroswap's optimal routing

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#249]
- [x] Code `executeRoute()` function
- [x] Code `generateRoute()` function

**Comment by abstract829** [comment]
to test after merge https://github.com/soroswap/frontend/pull/263

**Comment by joaquinsoza** [comment]
I suggest modifying our approach to handling trade routes by incorporating the route fetching directly within useBestTrade. This change aims to improve efficiency by eliminating delays between the user initiating a swap and the SDK querying the backend for the route. By fetching the route as part of the trade generation process in useBestTrade, we can ensure the expected amount out is accurately calculated based on the route, addressing the current issue where it's based on reserves and updated at swap time. It's necessary to update the trade object to include the route from the sdk, reflecting the accurate expected output and price impact in the SwapComponent. Given the introduction of the router and its response patterns, we should also evaluate the structure of the trade object, particularly the relevance of the swaps[] array, to align with our updated trading logic. This adjustment is aimed at enhancing the trading process's accuracy and responsiveness.
