### ISSUE TITLE
Improve caché / Token list

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#259]
Currently:
- User enters to Soroswap for the first time, Soroswap extracts the token list from the API.
- The token list, plus other info is stored in caché.
- If the token list changes (testnet reset), the user needs to clean caché

What we want:
- Caché should expire after certain time
- Evaluate if the caché is really usefull

**Comment by abstract829** [comment]
to test after merge https://github.com/soroswap/frontend/pull/263
