### ISSUE TITLE
Xbull & Xbull Signer Implementation

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#269]
Make it work!

**Comment by MattPoblete** [comment]
- **Add support to change chains on frontend.**
- [ ] Set available chains (use @soroban-react/chains)
- [ ] Refactor connect button: When address is available display the address & the active chain.
- [ ] Add to the connected button a modal that displays a dropdown to change between chains.
- [ ] Show a toast to update the result.
- **Add support to Xbull Signer (mobile).**
- [ ] On xBullSigner app (mobile version) should not ask if is installed, it should connect anyways
- [ ] Test mobile connection on xBullSigner app
