### ISSUE TITLE
define and implement integration testing

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#283]
- [ ] Make wdio great again (make it work as it is right now)
- [ ] Update Freighter extension to latest version (5.17.2) and update tests to work with new freighter:
- [ ] Add remove liquidity test

**Comment by MattPoblete** [comment]
Created https://www.workana.com/job/testing-automatizado-de-frontend to search for freelancers.
Invited:
- ✖️ https://www.workana.com/freelancer/ec88483a81adfa1449413bea6da6b214 
 
- ⏳ https://www.workana.com/freelancer/bfbba7e1c6910d362be02187430bafa2 *

- ⏳ https://www.workana.com/freelancer/bd12e8d25e3026c850dbe21000828c0b 
- ⏳ https://www.workana.com/freelancer/61f8979e95b47c9eb3fbd8274826ddab
