### ISSUE TITLE
trustline entry is missing for account, when quoting Stellar Classic Asset without connecting wallet

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#300]
- Use Mainnet (or Testnet) and try to quote an existing pair with Stellar Classic Asset

![Screenshot from 2024-03-08 16-18-59](https://github.com/soroswap/frontend/assets/2274485/eb65e2b4-d4cc-4a10-b203-7ec58f47c352)

**Comment by esteblock** [comment]
This is because we are simulating using the address of the private key in .env
However this address might not have trustline with every asset.
We need to have a mock address that has trustline with every asset to solve this

**Comment by esteblock** [comment]
- When wallet is conneced, please use public key of wallet connected @benjaguiloff

**Comment by chopan123** [comment]
solved in PR #313
