### ISSUE TITLE
Minimum XLM Balance

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#304]
Currently the frontend proposes to use MAX amount of XLM
But in fact accounts have a reserved used of XLM for each trustline + other reservec XLM balance
- CHeck how to see the available XLM balance
- Max should be available - fees?
- How to show this to the user?

**Comment by benjaguiloff** [comment]
PR: https://github.com/soroswap/frontend/pull/344

**Comment by chopan123** [comment]
Can't see MAX button on swap

MAX button on add liquidity adds all XLM

**Comment by esteblock** [comment]
@MattPoblete 

@chopan123 @joaquinsoza  
Another 2 problems here are:
1)
Currently:
- Dapp waits you to put an amount in order to simulate the tx and know the txfees.
- then when you press MAX, it calcualtes again and so on, infinite loop

Proposed:
- Take an average of tx fees for every type of tx (swap, add liquidity, remove liquidity, create LP),
and put it as a known hardcoded value (in config file)

2)
Because starts calculating fees straight away, and does not waints until it's an accepted trade, it calculates fees with 0 output amount, having the `    RouterInsufficientOutputAmount = 507,` error allways
```
Error fetching network fees: Error: host invocation failed
Caused by:
    HostError: Error(Contract, #507)
```
