### ISSUE TITLE
After wrapping a new asset, in AddLiquidity says "Insufficient Balance", need to refresh

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#305]
- Create a new asset or buy an asset outside of the list in StellarTerm
- Add liquidity, wrap. Not it will say Insufficient Balance

Balance check checks balance in Soroban and not in Horizon?

**Comment by chopan123** [comment]
Tested in testnet, It asked me to wrap twice while adding liquidity

**Comment by chopan123** [comment]
El balance aparece bien pero igual me tira insuffient asset balance

![Image](https://github.com/soroswap/frontend/assets/18266350/053a7721-a7c2-49cd-bd6c-e6f2064d6b05)
