### ISSUE TITLE
Stellar Asset names are too long and we have a display bug

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#308]
![Captura_de_pantalla_2024-03-11_185102](https://github.com/soroswap/frontend/assets/2274485/54a97fcd-dacb-41fe-a05d-4edb70d76e4f)
![Captura_de_pantalla_2024-03-11_184821](https://github.com/soroswap/frontend/assets/2274485/d39c0a2d-e241-4b00-a020-169dd427cf0c)

**Comment by esteblock** [comment]
For Stellar Classic Assets, when we get the name to display, we should either cut before the ":", or show "symbol"

**Comment by MattPoblete** [comment]
Created pull request https://github.com/soroswap/frontend/pull/319.
The names are currently displaying as:


![Image](https://github.com/soroswap/frontend/assets/86752543/6697d493-2d22-4747-854b-a5266dcb71c8)



![Image](https://github.com/soroswap/frontend/assets/86752543/5973323f-f23c-42d9-a347-2724fc8c1d68)
