### ISSUE TITLE
[Bug] CurrencySearch wrong balancess

### ISSUE THREAD

**Issue by MattPoblete** [soroswap/frontend#323]
User story:
The balance displayed for EURC-circle in the CurrencySearch component exhibits erratic behavior. Initially, the correct value (10) is displayed, but then it changes to 0 for no apparent reason, even when the balance in the wallet has not changed.

Steps to Reproduce:
[Mainnet]

> Make sure you have enough token balance
1. Access the CurrencySearch component on: add liquidity > select token
2. Search for "EURC-circle".
3. Observe the balance value.
4. Wait a few seconds.
5. Observe how the balance value changes to 0.

Evidence: 
![image](https://github.com/soroswap/frontend/assets/86752543/60950b7f-4cf1-404b-aec8-b19789e6cff5)
![image](https://github.com/soroswap/frontend/assets/86752543/0720e8f9-88ec-42d1-af9a-03f9853c3acf)

**Comment by MattPoblete** [comment]
@esteblock 
In order to help future us to understand correctly the issue I would like ask:
- Is this behavior exclusive to EURC-circle? 
- Has it happened to you with other tokens? 
- Has it happened more than once or was it a one-time occurrence?
- Is this behaviour exclusive from mainnet or it has occured on testnet / standalone?

**Comment by esteblock** [comment]
Don't know to any of the questions. Please debug and test...

**Comment by MattPoblete** [comment]
EURC circle addres: EURC:GDHU6WRG4IEQXM5NZ4BMPKOXHW76MZM4Y2IEMFDVXBSDP6SJY4ITNPP2

**Comment by abstract829** [comment]
this was solved before and is fixed

https://streamable.com/9648jz
