### ISSUE TITLE
[Feature] Format decimals on Soroswap

### ISSUE THREAD

**Issue by MattPoblete** [soroswap/frontend#324]
Add feature:
When components display balances with a decimal equal to 0 (e.g.: XXXX.000, XXXX.0000000, …) display the number in the format XXXX.0 (TBC)
- [ ] Create a helper to parse the value.
- [ ] Identify all components displaying balances.
- [ ] Add this feature to all components displaying balances.

![image](https://github.com/soroswap/frontend/assets/86752543/1d692002-259f-40a2-812a-82983991bf6a)
![image](https://github.com/soroswap/frontend/assets/86752543/68766d7e-cc61-45cd-949a-e56b9ef6d8e1)
![image](https://github.com/soroswap/frontend/assets/86752543/32d4e0e2-6fdb-444d-baae-70b2e2c787ac)
![image](https://github.com/soroswap/frontend/assets/86752543/f9769b3d-9ca3-4708-8ba3-8672b54aae6c)

**Comment by MattPoblete** [comment]
@esteblock when the balance decimals is 0, they should display as:
- [ ] XXXX.0
- [ ] XXXX

**Comment by esteblock** [comment]
Without decimals if x.0
