### ISSUE TITLE
[Bug] Display in mobile version dont let user see the action button

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#334]
Currently all is in the same column:
- "You sell"
- SYMBOL
- Name
- Amount
- Dollar equivalent

![4-Hana-Confirmation-Menu](https://github.com/soroswap/frontend/assets/2274485/b2338de9-eaeb-4168-ac1c-3011a54164bf)

Proposed solution: Create two collumns:
Left collumn:
- "You sell"
- SYMBOL
- Name

Right column:
- Amount (bigger, please!)
- Dollar equivalent

Very similar as in the quote section! (maybe copy / paste) ????
![3-Hana-Quote](https://github.com/soroswap/frontend/assets/2274485/d86399fd-bcdb-4c60-b8d3-bdd7e0081583)

**Comment by chopan123** [comment]
Don't see any change after merging :/
