### ISSUE TITLE
Liquidity positions don't automatically appear when changing from testnet to mainnet

### ISSUE THREAD

**Issue by benjaguiloff** [soroswap/frontend#337]
**Describe the bug**
If a user has their wallet set on Testnet and changes it to Mainnet, the Soroswap frontend will update, but will show no Liquidity Positions unless the user manually refreshes the page and reconnects the wallet.

**To Reproduce**
Prerequisite: have Liquidity Positions in at least 1 pool on Mainnet.
1. Set your wallet to the Testnet network
2. Go to the Soroswap app
3. Change the wallet's network to Mainnet
4. See the message "No liquidity found."
5. Refresh the page and reconnect the wallet
6. See the Liquidity Positions

**Expected behavior**
Soroswap should automatically show the correct Liquidity Positions when the user changes networks.

**Screenshots**
When wallet is set to Testnet:
<img width="629" alt="image" src="https://github.com/soroswap/frontend/assets/48481681/036dfc2d-eb2e-494f-b93b-3f09d13ad6a9">

After changing network to Mainnet:
<img width="647" alt="image" src="https://github.com/soroswap/frontend/assets/48481681/095bb55e-3007-46f4-8292-a6ee38e4af1d">

After refreshing and reconnecting the wallet:
<img width="627" alt="image" src="https://github.com/soroswap/frontend/assets/48481681/47e1520b-df21-4c60-80c2-da12c900df14">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 122.0.6261.131
 - Wallet: Freighter

**Additional context**
Problem does not happen when changing from Mainnet to Testnet, only the other way around.

**Comment by abstract829** [comment]
this was solved before and is fixed

https://streamable.com/5uc08v
