### ISSUE TITLE
Adapt backend info to new getPoolInfo

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#338]
https://github.com/soroswap/backend/issues/103
Every when there should be a value, put a `-`

**Comment by esteblock** [comment]
Hide
![Uploading Screenshot from 2024-03-26 15-30-31.png…]()

**Comment by esteblock** [comment]
En: 
![Screenshot from 2024-03-26 15-34-34](https://github.com/soroswap/frontend/assets/2274485/7aefda16-a795-4a9b-b962-ff16a04bba1c)

Ocultar: Volume 24H /  Fees 24H

Dejar: TVL

**Comment by benjaguiloff** [comment]
PR: https://github.com/soroswap/info/pull/37/

**Comment by chopan123** [comment]
merged
