### ISSUE TITLE
Add XLM alias in URL

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#352]
the URL to swap could be possible to do /swap/XLM/<contract>  currently XLM doesnt work and needs to be the xlm contract address

Por ejemplo, en vez de tener:
`https://app.soroswap.finance/swap/CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA/CAZQYRFG7A2CZTZ2NEODHZGIOORFFKOEFV7WWZOBJEYXER56ASCUBD7P`
aceptar 
`https://app.soroswap.finance/swap/XLM/CAZQYRFG7A2CZTZ2NEODHZGIOORFFKOEFV7WWZOBJEYXER56ASCUBD7P`

**Comment by joaquinsoza** [comment]
https://github.com/soroswap/frontend/pull/361
