### ISSUE TITLE
Explore how to sign `redeem` and `issue` tx with wallet 

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#356]

**Comment by joaquinsoza** [comment]
useInkhaton exports a "activeSigner" which then can be used to sign transactions with

```ts
const signed = await activeSigner?.signPayload(payload);
const signed = await activeSigner?.signRaw(payload);
```

**Comment by MattPoblete** [comment]
useIssuePallet hook

portal/src/hooks/spacewalk/useIssuePallet.tsx at main · pendulum-chain/portal

useIssuePallet:

Primero, se extrae api del estado devuelto por el provider. Esta api es una instancia de la API de Polkadot que permite interactuar con la blockchain.

El hook retorna un objeto que contiene tres funciones: getIssueRequests, getIssueRequest y createIssueRequestExtrinsic.

getIssueRequests:Utiliza la función api.query.issue.issueRequests.entries de la API para obtener todas las entradas de issueRequest existentes. Si no hay entradas, devuelve un array vacío. Si hay entradas, las mapea a un objeto que contiene el ID de la solicitud y la solicitud misma.

getIssueRequest: Obtiene un issueRequest específico por su ID a través de la función api.query.issue.issueRequests(issueId). Si la request existe y tiene un valor, devuelve un objeto con el ID de la y el contenido de la request misma. Si la solicitud no existe o no tiene un valor, devuelve undefined.

createIssueRequestExtrinsic: Es una función que crea una transacción extrínseca para crear la operación issueRequest. La función api.tx.issue.requestIssue(amount, vaultId) toma dos argumentos: amount, que es la cantidad a emitir, y vaultId, que es el ID del vault que recibirá los tokens emitidos.

useRedeemPallet hook

portal/src/hooks/spacewalk/useRedeemPallet.tsx at main · pendulum-chain/portal

useRedeemPallet:

Primero, se extrae api del estado devuelto por useNodeInfoState(). Esta api es una instancia de la API de Polkadot que permite interactuar con la blockchain.

El hook retorna un objeto que contiene tres funciones: getRedeemRequests, getRedeemRequest y createRedeemRequestExtrinsic.

getRedeemRequests: Utiliza la función api.query.redeem.redeemRequests.entries() de la API para obtener todas las entradas de redeemRequest existentes. Si no hay entradas, devuelve un array vacío. Si hay entradas, las mapea a un objeto que contiene el ID de la solicitud y la solicitud misma.

getRedeemRequest: Obtiene un issueRequest específico por su ID a través de la función api.query.redeem.redeemRequests(issueId). Si la request existe y tiene un valor, devuelve un objeto con el ID de la y el contenido de la request misma. Si la solicitud no existe o no tiene un valor, devuelve undefined.

createRedeemRequestExtrinsic: es una función que crea una transacción extrínseca para solicitar una operacion de redeem. Utiliza la función api.tx.redeem.requestRedeem la cual recibe tres argumentos: amount, que es la cantidad de tokens a solicitar, stellarAddress, que es la dirección Stellar a la que se enviarán los tokens redimidos, y vaultId, que es el ID del vault que recibirá los tokens. Si api no está definida, devuelve undefined.
