### ISSUE TITLE
Bridge: Show pendulum user's information

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#393]
On bridge tab, on bridge component, add a similar button that shows Stellar's user address (or something similar) to show Pendulum's user information (wallet, chain, or other if I forget something)

**Comment by MattPoblete** [comment]
Design mockup

![Image](https://github.com/soroswap/frontend/assets/86752543/dcc8eb10-ec2c-4331-b712-0d846e17c38b)

**Comment by MattPoblete** [comment]
Current implementation

![Image](https://github.com/soroswap/frontend/assets/86752543/e50e2e5f-ad57-4fc9-8525-5ebe9d14b2ba)
