### ISSUE TITLE
Bridge: Mouse over on bridge fee

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#394]
Pendulum bridge fee is currently 0, but it may not be in the future, add a mouse over on modal's information, on bridge fee to explain that. (on pendulum official bridge frontend you may find a good message to copy)

**Comment by abstract829** [comment]
![Image](https://github.com/soroswap/frontend/assets/56497105/65faa187-5763-484d-a3e5-2221cd0457c1)
