### ISSUE TITLE
Bridge: Disable "Send" button when XLM input is greater than available balance

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#403]
**Describe the bug**
Webapp allow one to bridge a balance between user's XLM balance and available balance

**To Reproduce**
1. Go to 'http://localhost:3000/bridge'
2. Type an amount greater that available balance, but less than user balance
5. See error
**Expected behavior**
It should be disabled

**Comment by joaquinsoza** [comment]
Its only happening with XLM because of the "available balance" and it happens too in Swap section
