### ISSUE TITLE
Bridge: Follow steps on modal when bridging tokens to and from pendulum

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#406]
Show in the transaction modal the steps of the bridge process, Propose a frontend beatiful view: 
for example,

when bridging to pendulum from stellar we have 2 steps. one for signing pendulum tx (show 1/2)  and then receiving (show 2/2) or 1 of 2.

When bridging from Stellar to Pendulum we have 3 steps.

**Comment by MattPoblete** [comment]
Issue steps:

1. Confirm.
2. Approve in polkadot wallet.
3. Await for confirmation on polkadot network.
4. Approve & Sign in Stellar wallet.
5. Await for transaction confirmation.
6. Result (Success, failed).

Reddem steps:

1. Confirm.
2. Approve in polkadot wallet.
3. Await for confirmation on polkadot network.(”Waiting on transaction confirmation on pendulum network”).
4. Result (Success, failed).

**Comment by MattPoblete** [comment]
![Image](https://github.com/soroswap/frontend/assets/86752543/66e9dd23-86aa-41b2-bece-fc17376a3630)

**Comment by MattPoblete** [comment]
Created Pull reques https://github.com/soroswap/frontend/pull/429!

**Comment by MattPoblete** [comment]
Found a bug: When selecting assets for first time, the state doesn't update automatically.
