### ISSUE TITLE
Create Video Tutorial: How to Bridge from Stellar to Polkadot using Pendulum

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#420]
- [x] Create a tutorial video.
- [x] Create a text tutorial

Check this one: https://youtu.be/OnkBarC-BW0?feature=shared
Explain each step and highlight the fact that we can sign all transactions in the step witthout going of the Sororswap.Finance dapp.
Do Bridge from Stellar to Polkadot and from Polkadot to Stellar.

Use Soroswap.Finance to swap and get some tokens (ex. first, buy NGNC, then bridge).

Explain every step

**Comment by MattPoblete** [comment]
Swap XLM -> NGNC ; Bridge NGNC to NGNC.s on pendulum

**Comment by MattPoblete** [comment]
Video tutorial:
https://drive.google.com/file/d/1d0d-V7j4d9r-w6maVksiplSpgmR0lR2_/view?usp=drive_link

**Comment by MattPoblete** [comment]
Tutorial v2:
https://drive.google.com/file/d/1A6UpFh83W9v8vm9GQO4wL6kUkZPVFDXv/view?usp=drive_link
