### ISSUE TITLE
[Bridge] Improve how we show the Stellar/Pendulum addresses and balance

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#422]
Currently:
![Screenshot from 2024-04-30 10-21-13](https://github.com/soroswap/frontend/assets/2274485/658f46f4-d453-48d5-aaca-c4877f198db8)
Currently the user might be confused.

I wanna see that in Bride component, after the "Bridge" title:
- Pendulum [Stellar] [Amount] PEN
- Stellar [Address] [Amount] XLM

**Comment by MattPoblete** [comment]
@esteblock  Could you please add a wireframe to make it more specific?
