### ISSUE TITLE
[General] check if dapp works with node 20.10.0

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#443]
Cypress is currently working with node 20.10.0 

We need to make sure our app could work with node 20.10.0, if not we may need to build a cypress image for our testing propose

Check with current version and with 20.10.0 (no vaya a ser que algo se haya roto en v18) :
 - [x] Wrap contract
 - [x] Set trustline
 - [x] Swap
 - [x] Add
 - [x] Remove

**Comment by MattPoblete** [comment]
Everything works fine!
