### ISSUE TITLE
Evaluate Anchors to include

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#468]
Evaluate (at least): [anchors.stellar.org](https://anchors.stellar.org/)
- Anclap
- Meru
- BRLA
- NGNC (link.io)

**Comment by MattPoblete** [comment]
- [x] Anclap [LATAM]
- [x] MyKobo [EU]
- [x] Crypto.com  [U.S. / ww]
- [ ] Meru
- [ ] BRLA
- [ ] NGNC (link.io)
- [ ] MoonPay [EU]
