### ISSUE TITLE
Liquidity Pool Info show 0 for token balances

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#496]
**Describe the bug**
Users that have LP positions can see corectly their percentage of the participation, and units of the LP token, but they se "0" on how much of each token that position represent

![LiquiditYPoolInfoBug](https://github.com/user-attachments/assets/e9316084-a46a-4a7b-a0ca-183c1cb7d902)

**To Reproduce**
1. Add liquidity
2. Check your liquidity

**Expected behavior**
See the amount of token that LP postion represents

**Comment by DApps-Representative** [comment]
> **Describe the bug** Users that have LP positions can see corectly their percentage of the participation, and units of the LP token, but they se "0" on how much of each token that position represent
> 
> ![LiquiditYPoolInfoBug](https://private-user-images.githubusercontent.com/2274485/348135658-e9316084-a46a-4a7b-a0ca-183c1cb7d902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzUyODQsIm5iZiI6MTcyMDc3NDk4NCwicGF0aCI6Ii8yMjc0NDg1LzM0ODEzNTY1OC1lOTMxNjA4NC1hNDZhLTRhN2ItYTBjYS0xODNjMWNiN2Q5MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMDkwMzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBkZDYzNTY2MjcyNzQ3N2M5NTJmMTY1OTg2YTBjY2UwNTU2NjdhMGNjMGFiNThlZDZkYjFhZWJhZTIxOTk1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pZ-MLQ87knEHQ9TmlkXQra5rxMW0sKzmSbXJj4nuQV4)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Add liquidity
> 2. Check your liquidity
> 
> **Expected behavior** See the amount of token that LP postion represents

Hey there @esteblock   ,

Thank you for reaching out! hi, it seems your address was blacklisted: kindly refresh your wallet, if the issue persists,then your query would be best dealt with by the support team.
 I’ll have to refer you to the official support Team with the ticket ID SRW7463
 
Please see the link below to our dedicated support line: 
 [Soroswap Network Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.

**Comment by chopan123** [comment]
Can't reproduce, maybe it has been fixed before
