### ISSUE TITLE
2 update soroban-react and stellar-sdk

### ISSUE THREAD

**Issue by abstract829** [soroswap/frontend#501]

**Comment by esteblock** [comment]
https://github.com/paltalabs/soroban-react/commit/84afb7cac95bd124a88d4d67aea980ed39288632

**Comment by chopan123** [comment]
- [ ] publish new version of Soroban-react
- [ ] Use this new version on soroswap frontend in combination with latest stellar-sdk version ?
- [ ] Review that soroban-react and frontend uses the same stellar-sdk version.

**Comment by chopan123** [comment]
- [ ] Review automatic test
- [ ] Do frontend testing manually, in testnet and mainnet (swap exact in, swap exact out, add liquidity, create pair, remove liquidity, wrap, create trustline)


use cheescake to create new tokens

**Comment by MattPoblete** [comment]
- [x] Review automatic test
- [x] Manual Swap Testnet
- [x] Manual Swap Mainnet SDEX
- [x] Manual Swap Mainnet Soroban
- [x] Add liquidity Testnet
- [x] Remove liquidity Testnet
- [x] Add liquidity Mainnet
- [x] Remove liquidity Mainnet
- [x] Wrap token Testnet
- [x] Set trustline Mainnet
- [x] Set trustline Testnet
