### ISSUE TITLE
Error: Handle error when contract does not exist

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#51]
How to replicate:
- Deploy in Futurenet
- Configure your wallet to use Futurenet in localhost:8000
- Run quistart node with Standalone in port 8000
- Try to use Soroswap

Current: Nothing happens, there is only an error in the console

```
error: HostError
Value: Status(HostStorageError(AccessToUnknownEntry))
```

What we want:
Warn the user

**Comment by joaquinsoza** [comment]
The config required in freighter for futurenet see [soroban-example-dapp](https://github.com/stellar/soroban-example-dapp) Backend Option 2 for reference, the scripts are not the same but you can see the details for the freighter wallet

![Image](https://github.com/soroswap/frontend/assets/34905663/c9e6af61-ecab-4003-8ed5-b85798517d48)

you should run 
```bash
bash scripts/deploy_tokens_n_pairs.sh futurenet 8
```
