### ISSUE TITLE
1 Custom slippage triggers an unhandled error

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#517]
@MattPoblete Add more details: step to reproduce, browser, etc.

**Comment by MattPoblete** [comment]
Bug detected on msEdge.
Steps to reproduce:
 - Navigate to https://app.soroswap.finance/swap
 - Click on the settings button (Top right)

![Image](https://github.com/user-attachments/assets/1ca2bf7d-e5eb-49d2-be78-ffebd6d4d3b2)

 - Open max slippage dropdown 


![Image](https://github.com/user-attachments/assets/0c287682-1abb-4f4f-acb7-511cd3c9d2c0)


 - Click on the "custom" button or try to change the value in the input field


![Image](https://github.com/user-attachments/assets/ea1597ff-1b53-4b73-a89c-35451e6ad317)

- The app will crash


![Image](https://github.com/user-attachments/assets/cda01732-4c26-4888-be2f-73b02852078c)
