### ISSUE TITLE
3 Find a better way to recognize Stellar Classic Assets from Soroban Contracts

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#519]
I took the CODE:ISSUER from the name of the token here:

https://github.com/soroswap/frontend/commit/f2c6987df631a2a64dd0d1bf57af56d955774f7c

This is in order to let the user create a trustline with a stellar classic asset that its not in the list.
However this might have a risk of a user
1) creating a token with a name with abother CODE:ISSUER
2) social engineer a second user to use that soroban address
3) let him think that it is the CODE:ISSUER

We need a way to know 100% if a contract is a wrapped stellar classic asset

**Comment by chopan123** [comment]
I think it could be a check like:
```javascript
function checkContractId(contractId: string, code: string, issuer: string): boolean {
	const asset = new Asset(code, issuer);
    return asset.getContractId() === contractId;
}
```
