### ISSUE TITLE
2 Swap in SDEX randomly fails with "cannot create path payment"

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#525]
![image](https://github.com/user-attachments/assets/19ad4a33-f64b-4436-97f4-5bbd833d259e)
Difficult to replicate.
Happens soomethimes.

Do research

**Comment by chopan123** [comment]
did you change slippage?

**Comment by chopan123** [comment]
Improve error handling

**Comment by esteblock** [comment]
- [ ] Handle errors from Horizon
- [ ] Check Horizon configuratio
- [ ] ask in Discord why is this happening? Why StellarTerm shows paths much more simple

check
```
 try {
      const send = serverHorizon.strictSendPaths(args.assetFrom, args.amount, [args.assetTo])
        .call().then((res) => res.records);
```

**Comment by MattPoblete** [comment]
https://github.com/stellarterm/stellarterm
stellarterm repo
