### ISSUE TITLE
1 Feature aggregator paths on swap details

### ISSUE THREAD

**Issue by MattPoblete** [soroswap/frontend#526]
Currently when a swap is made using the aggregator the swap details don't show the path, we should implement a custom solution for this case that displays all the aggregator paths and their distribution.
![image](https://github.com/user-attachments/assets/2c5d60b5-f5c2-437c-8725-4db82092a96d)

Goal:
![image](https://github.com/user-attachments/assets/17b11d54-9d15-4ed4-8b61-90e6a07d7dd2)

**Comment by esteblock** [comment]
@MattPoblete 
We still need info with which Protocol is going

![Image](https://github.com/user-attachments/assets/5e4ac5f9-d4ed-4aee-9070-f760835a7dd6)

**XLM >USDC > (100%)**

should be

**Soroswap XLM >USDC > (100%)**




Also in modal is not being shown!!!!!



![Image](https://github.com/user-attachments/assets/32b9d4d4-4282-4f0c-a5fd-6dddab935b32)

**Comment by esteblock** [comment]
Hello @MattPoblete when is passing thorugh the Aggregator seems OK
![image](https://github.com/user-attachments/assets/aaac0f10-5acb-49f5-a31a-4573086b15e6)
![image](https://github.com/user-attachments/assets/ac8ef182-1927-4a4c-a65d-52abfe96ab8a)


**HOWEVER**

In Mainnet (without aggregator) is not showing incorrectly!

![image](https://github.com/user-attachments/assets/eab22c3b-7625-4506-81bf-3c78b7a711bb)
![image](https://github.com/user-attachments/assets/ba3eec2c-28b1-4b84-9046-3cb661e6e75b)


**TASKS**

- [ ] Fix when is not using aggregator (currently on Mainnet)
