### ISSUE TITLE
2 Bug: Transaction failed when passing through AMM token

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#528]
https://stellar.expert/explorer/public/contract/CDHBIACXSM5K2NFCCHQIJQNDJPHGPW4OHIYVXGCFMVT7PNLWXY4NGRNH

AMM token should not be used as it is marked as unsafe

**Comment by chopan123** [comment]
#525

**Comment by esteblock** [comment]
- [ ] Do some research to understand why is this case 
- [ ] Check time to live of variables (LP contract, variable in Factory, AMM contract)

**Comment by esteblock** [comment]
- [ ] Check UltraStellar API for path creation
- [ ] Analize price impact

**Comment by esteblock** [comment]
- [ ] Add script to check TTL of every contract that where involved in a specific transaction in https://github.com/soroswap/utility-contracts

- [ ] Write small blog post. in dev.to and share it in Stellar Discord Server.

- [ ] Find solution on how to bump this specific contract.
