### ISSUE TITLE
3 Soroswap is not suggesting to set trustline for some Stellar Assets

### ISSUE THREAD

**Issue by chopan123** [soroswap/frontend#534]
try swapping: CAPIOPSODD5QP4SJNIS4ASUWML4LH7ZEKTAPBJYZSMKXCATEKDZFKLHK

in stellar expert does not exist https://stellar.expert/explorer/public/search?term=CAPIOPSODD5QP4SJNIS4ASUWML4LH7ZEKTAPBJYZSMKXCATEKDZFKLHK

it means it need to be wrapped

go to Swap, try swapping xlm for Nuna, its not suggesting to wrap, or to set trustline

**Comment by esteblock** [comment]
- [ ] Understand
- [ ] Try to generate a way to replicate the error
- [ ] Discuss with @chopan123 to see if it makes sense to handle this issue

**Comment by chopan123** [comment]
checked with CAWSVMCGBT4YEDH4PK64TZ3IRTXDHZJ6PDSSUARFLKRG2H3MUBLTVQ6C
