### ISSUE TITLE
Bug: First asset reset to XML on protocols changes

### ISSUE THREAD

**Issue by MattPoblete** [soroswap/frontend#561]
Current Situation: When the protocols config changes in the frontend (Example: From using only Soroswap to use Soroswan AND Phoeni), the first asset always reset to XLM, and sometimes, it changes to a negative ammount

Expected Situation: Assets and required quote amound should not chane

**Comment by Jemiiah** [comment]
@esteblock can I work on this isssue with an ETA of 48 hours

**Comment by tasneemtoolba** [comment]
Can I attempt this issue?

**Comment by vijay-kesanakurthi** [comment]
Could I take a shot at this?

**Comment by thiagoulloa** [comment]
Can I work on this as my first contribution?

**Comment by 0xdevcollins** [comment]
Is it okay if I tackle this?

**Comment by Kaminar-i** [comment]
Please give me a chance on this

**Comment by Benjtalkshow** [comment]
I'd love to give this a go.

**Comment by sigmadawg** [comment]
im a newbie contributor, i'd be grateful if you'd give me the opportunity to work in this.

**Comment by PrincesoDan** [comment]
I would like to take on this task. I haven't worked with the soroswap/frontend repository before, but I think it could be resolved as follows:

    Ensure that the asset values are not reset when changing protocols.

    Avoid having the state of the selected asset replaced by default. Changing the protocol configuration should not modify the state of the previously selected assets.

    Preserve the state of the selected asset.

    We could use a control structure that preserves the previous state of the selected assets. To achieve this, perhaps review the frontend's route configuration file, where protocol changes and asset updates are handled. We could apply the same logic that preserves the state of the assets and amounts, and prevents negative amounts.

**Comment by esteblock** [comment]
Hello everybody, Thanks for the interest. I assigned @thiagoulloa as I want to see a Github profile focused on Web3 / Blockchain.
Linkedin in profile also works.
For the others, please work on your github profiles.

**Comment by esteblock** [comment]
> Can I work on this as my first contribution?

Hello, I dont se any progress. 
Can you please open at least a draft PR?
If you need anything please reach on Discord https://discord.com/invite/G8c98rhfqw #onlydust channel

**Comment by thiagoulloa** [comment]
I've just made the PR!

**Comment by esteblock** [comment]
> I've just made the PR!

Hello, next time please refer this issue on the PR>
And also link the PR into this issue
