### ISSUE TITLE
250 USD Improve List of Tokens

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#565]
When swapping, a list of tokens appear,
list of tokens should be sorted by tokens with more volume (check info repo)

**Comment by Ugo-X** [comment]
please can i be assigned this

**Comment by PedroCo3lho** [comment]
Can i work on this?

**Comment by Ugo-X** [comment]
Thanks chief, will get started

**Comment by Ugo-X** [comment]
@esteblock GM, i have setup the project and connected a wallet but when i try to swap, no token is shown. it returns no tokens found. I don't know if there's something i'm missing?

**Comment by esteblock** [comment]
> @esteblock GM, i have setup the project and connected a wallet but when i try to swap, no token is shown. it returns no tokens found. I don't know if there's something i'm missing?

Hello please reach on Discord https://discord.com/invite/G8c98rhfqw

**Comment by esteblock** [comment]
> @esteblock GM, i have setup the project and connected a wallet but when i try to swap, no token is shown. it returns no tokens found. I don't know if there's something i'm missing?

Go to the #onlydust channel so we can discuss further

**Comment by Ugo-X** [comment]
Alright ser

**Comment by Ugo-X** [comment]
@esteblock sent a private message. I do not have permission to send a chat in the groups

**Comment by esteblock** [comment]
Hello @Ugo-X shall we assign someone else?

**Comment by Ugo-X** [comment]
> Hello @Ugo-X shall we assign someone else?

Will send a PR early tomorrow

**Comment by esteblock** [comment]
We still have 250 USD as budget for this issue

**Comment by Ugo-X** [comment]
Should I still fix the issues you listed on this cause I saw you closed my PR?

**Comment by esteblock** [comment]
Yes, I closed the PR as it was not completed as Discussed on Discord.
I will wait to asign someone else @Ugo-X

**Comment by Ugo-X** [comment]
Alright

**Comment by Ugo-X** [comment]
Alright

**Comment by 0xdevcollins** [comment]
Hello I'm 0xdevcollins from discord

**Comment by Benjtalkshow** [comment]
Hello @esteblock  Can i work on this task? I already dropped a message on discord.

**Comment by Michaelkingsdev** [comment]
Let me work on this and deliver as fast as possible. Thanks

**Comment by esteblock** [comment]
asigned @thiagoulloa

**Comment by thiagoulloa** [comment]
Just made the PR!

#571

**Comment by esteblock** [comment]
Hei @thiagoulloa 

![image](https://github.com/user-attachments/assets/2c423394-9cbc-41ed-9094-d254b5918908)


I cannot even se the token list
