### ISSUE TITLE
useTokenFromActiveNetwork -> Search token

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/frontend#60]
In the search currency modal, when you type and address the app should look for the token information in the blockchain

The function is already there and its being used, but it returns null it should return a new TokenType object with its information

```
src/hooks/useTokens.tsx Line: 82
```

In this line there is the function useTokenFromActiveNetwork, should look for the token information (id, address, symbol, name)

There is a lot of commented code from the uniswap interface, deleted if there is no use to it

**Comment by esteblock** [comment]
We have changed the design
