### ISSUE TITLE
Settings: modal / button - import components from Uniswap

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/frontend#68]
Add this settings modal/context that opens when the settings icon is clicked

![Image](https://github.com/soroswap/frontend/assets/34905663/f8eb6597-5493-4f14-b40b-f7745b6d431a)

Including
- [x] Local Routing
- [ ] Max Slippage
- [x] Transaction deadline

Please refer to [uniswap interface](https://github.com/Uniswap/interface) for the styled components and how the component is compose. I've been running this project locally to see the files and its workings.

**Comment by esteblock** [comment]
@chopan123 working in https://github.com/soroswap/frontend/pull/81

**Comment by chopan123** [comment]
![Image](https://github.com/soroswap/frontend/assets/18266350/3b374356-7ffc-4c29-879c-0054a653fa40)
![Image](https://github.com/soroswap/frontend/assets/18266350/7ec81453-b315-41c3-9fcd-ad018cd8d391)
