### ISSUE TITLE
Transaction Submitted Modal

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/frontend#72]
### Dependant of #71 

This modal will be used in multiple situations, every time a transaction is submitted to the blockchain, for now it should show after Swapping and providing liquidity

Please refer to [uniswap interface](https://github.com/Uniswap/interface) for the styled components and how the component is compose. I've been running this project locally to see the files and its workings.

**Comment by esteblock** [comment]
For swap refer to: https://github.com/soroswap/frontend/issues/97
