### ISSUE TITLE
Liquidity Pools Add liquidity

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/frontend#74]
### V2 Provide liquidity 
The add liquidity button should take you to this screen, where you can select 2 tokens and provide liquidity to them or create the pair if it doesnt exist, the settings menu is exactly the same as #68 

![Image](https://github.com/soroswap/frontend/assets/34905663/ecaf3f59-b47c-4206-8d34-1596c71e6137)

You should be able to make it work right away, provide liquidity old component is already working, see how uniswap function works too see if we can improve ours

Please refer to [uniswap interface](https://github.com/Uniswap/interface) for the styled components and how the component is compose. I've been running this project locally to see the files and its workings.

**Comment by chopan123** [comment]
- [ ] Add deposit button
- [ ] Gather tokens info
    - [ ] Open modal that selects token
    - [ ] Use redux to define tokens to use
- [ ] Add settings component

**Comment by esteblock** [comment]
solve: 

- [ ] When clicking in " Create Pair", takes about 8 seconds

**Comment by esteblock** [comment]
- [ ] Primera vez funciona bien pero no hay un confirm modal ni transactoin sucess modal
- [ ] Cuando la liquidez ya exite, hay un problema con los montos
- [ ] Cuando el par no existe, debería salir una advertencia que el par no existe y el usuario puede hacer clic en crear par.
- [ ] También abrir confirma modal y transaction sucess modal

**Comment by esteblock** [comment]
- [ ] Solve: When first entering to Provide Liquidity, we have 2 warnings:

![Screenshot from 2023-09-07 10-57-49](https://github.com/soroswap/frontend/assets/2274485/923f8204-2396-4fa5-980c-a782598476c3)
![Screenshot from 2023-09-07 10-57-45](https://github.com/soroswap/frontend/assets/2274485/28da100a-07c8-43ca-80f0-061a17b2de39)

**Comment by esteblock** [comment]
- [ ] Solve: When selecting the first token we have another warning:
![Screenshot from 2023-09-07 10-58-04](https://github.com/soroswap/frontend/assets/2274485/06ac4205-369e-47bf-957e-82deb4b97bd3)

**Comment by esteblock** [comment]
- [ ] When pair exist, but there is no liquidity, some message should be shown that the user can choose the amount of tokens. Currently there is no message, no warning, no note:
![Screenshot from 2023-09-07 11-08-19](https://github.com/soroswap/frontend/assets/2274485/5383fe61-9ca9-4fe2-b438-d287e46efdc6)
![Screenshot from 2023-09-07 11-08-12](https://github.com/soroswap/frontend/assets/2274485/eb16ef6d-df0a-4e7b-9135-35dd654a1797)

**Comment by esteblock** [comment]
- [ ] When pair does not exist: Currently breaking. Should appear a warning that we can create the pair and appear: Create pair:
![Screenshot from 2023-09-07 11-00-21](https://github.com/soroswap/frontend/assets/2274485/6bdfb0e7-b735-412f-b77a-7117e1e9b693)

**Comment by esteblock** [comment]
- [ ] When providing liquidity for the first time. Currently appears "you are creating the pool". This is not true. I think that should be the same as any other pool.....

![Screenshot from 2023-09-07 11-11-25](https://github.com/soroswap/frontend/assets/2274485/ff15dbc0-8e05-40b9-aba4-1dc302a5b720)

**Comment by chopan123** [comment]
adding amount of LP token to receive (not hardcoded) 

![Image](https://github.com/soroswap/frontend/assets/18266350/117b2a98-f89a-427e-8d03-65996568bb66)

**Comment by chopan123** [comment]
I got rate and share of Pool with latest commit

**Comment by chopan123** [comment]
Summary of tasks:
- [ ] Add settings component
- [ ] Solve why going to /add is so slow
- [ ] Create pair when pair does not exist
- [ ] Add Transaction Success modal
- [ ] Solve Warnings:
  - [ ] When entering to /liquidity/add
  - [ ] When selecting first token
- [ ] Add message when pair exists but there is not liquidity (user can choose both amounts)
