### ISSUE TITLE
(Liquidity): calculatePoolTokenOptimalAmount(pairAddress, tokenAddress, inputAmount

### ISSUE THREAD

**Issue by esteblock** [soroswap/frontend#9]
Create function calculatePoolTokenOptimalAmount(pairAddress, tokenAddress, inputAmount → Calculate) optimalOtherAmount Given a contract_id (I mean pair contract address) an amount and a token Address it returns an integer that indicates what’s the optimal amount of the other token in the pair contract to deposit.
Check github preriphery contracts and uniswap sdk https://github.com/Uniswap/v2-sdk/
Write this in a good way.

**Comment by chopan123** [comment]
Específicamente 

https://github.com/Uniswap/v2-sdk/blob/main/src/entities/pair.ts

**Comment by esteblock** [comment]
We need to test after doing a swap
